Repository LNP-BP/rust-lnpbp, pull requests merged in 2020-09, with the labels that each got.

#101 Commit encoding tests for Assignments, Metadata and Seals
  src/rgb/contract/assignments.rs
  src/rgb/contract/field.rs
  src/rgb/contract/seal.rs
Labels: *privacy*, consensus, test

#104 Refactoring bp::Network into Chain and ChainParams: closes #102
  src/bp/chain.rs
  src/bp/dbc/types.rs
  src/bp/mod.rs
  src/bp/network.rs
  src/bp/strict_encoding.rs
  src/common/data_format.rs
  src/paradigms/strict_encoding.rs
  src/rgb/contract/data.rs
  src/rgb/contract/nodes.rs
  src/rgb/schema/script.rs
  src/rgb/schema/state.rs
  src/rgb/schema/types.rs
  src/rgb/stash/consignment.rs
Labels: *compatibility*, consensus, enhancement

#108 Fix tests locations
  src/bp/chain.rs
  src/bp/strict_encoding.rs
  src/paradigms/client_side_validation.rs
  src/paradigms/strict_encoding.rs
  src/rgb/contract/amount.rs
  src/rgb/contract/assignments.rs
  src/rgb/contract/data.rs
  src/rgb/contract/field.rs
  src/rgb/contract/mod.rs
  src/rgb/contract/seal.rs
  src/rgb/contract/testutils.rs
Labels: enhancement, test

#105 Exhaustive tests for enums
  src/bp/chain.rs
  src/bp/dbc/types.rs
  src/paradigms/strict_encoding.rs
  src/rgb/contract/data.rs
Labels: test

#107 RGB: hashing bulletproof commitments; closes #106
  src/paradigms/client_side_validation.rs
  src/rgb/contract/amount.rs
Labels: *scalability*, *security*, consensus, feature

#109 Add node testings
  Cargo.lock
  src/rgb/contract/nodes.rs
Labels: *privacy*, *security*, consensus, test
