Repository LNP-BP/rust-lnpbp, pull requests merged in 2020-10, with the labels that each got.

#122 LNP addresses: detailed implementation & test coverage
  Cargo.lock
  Cargo.toml
  src/lnp/session/node_addr.rs
  src/lnp/session/node_locator.rs
  src/lnp/transport/zmq.rs
Labels: enhancement, test

#119 Improvements in garbage testing macro
  src/paradigms/strict_encoding.rs
  src/rgb/contract/amount.rs
  src/rgb/contract/assignments.rs
  src/rgb/contract/data.rs
  src/rgb/contract/field.rs
  src/rgb/contract/seal.rs
  src/rgb/schema/types.rs
Labels: bug, test

#121 Added test coverage for schema::state.rs
  Cargo.lock
  contrib/test.sh
  src/rgb/schema/state.rs
Labels: *privacy*, *security*, test

#126 Bech32 encoding improvements for RGB types
  Cargo.lock
  Cargo.toml
  src/bp/chain.rs
  src/bp/dbc/spk.rs
  src/bp/dbc/types.rs
  src/rgb/bech32.rs
  src/rgb/contract/nodes.rs
  src/rgb/mod.rs
  src/rgb/schema/nodes.rs
  src/rgb/schema/schema.rs
  src/rgb/schema/script.rs
  src/rgb/stash/anchor.rs
  src/rgb/stash/disclosure.rs
  src/standards/lnpbp4.rs
Labels: documentation, enhancement, test

#128 v0.1 release candidate
  Cargo.lock
  Cargo.toml
  README.md
  contrib/depCargo.toml
  derive/Cargo.toml
  src/lnp/application/peer.rs
  src/lnp/mod.rs
  src/lnp/presentation/error.rs
  src/lnp/presentation/message.rs
  src/lnp/presentation/tlv.rs
  src/lnp/session/connection.rs
  src/lnp/session/node_addr.rs
  src/lnp/session/transcoders.rs
Labels: upstream

#130 README: fix build instructions
  README.md
Labels: ci, documentation

#125 Refactoring & test covering deterministic bitcoin commitments
  Cargo.toml
  src/bp/dbc/error.rs
  src/bp/dbc/keyset.rs
  src/bp/dbc/pubkey.rs
  src/bp/dbc/spk.rs
  src/bp/scripts/pubkey_parser.rs
  src/bp/scripts/script_pubkey.rs
  src/standards/lnpbp1.rs
  src/standards/mod.rs
Labels: enhancement, test

#133 Release v0.1
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  README.md
  derive/Cargo.toml
Labels: epic

#131 Primitive AEAD functionalities
  Cargo.toml
  services/src/lib.rs
  src/lib.rs
  src/lnp/session/mod.rs
  src/lnp/session/noise.rs
Labels: feature
