Repository LNP-BP/rust-lnpbp, pull requests merged in 2020-11, with the labels that each got.

#135 Implement Noise Handshake (BOLT8)
  services/src/esb/controller.rs
  services/src/rpc/client.rs
  services/src/rpc/server.rs
  src/lnp/application/peer_connection.rs
  src/lnp/mod.rs
  src/lnp/session/mod.rs
  src/lnp/session/noise.rs
  src/lnp/session/noise/act.rs
  src/lnp/session/noise/chacha.rs
  src/lnp/session/noise/conduit.rs
  src/lnp/session/noise/handshake.rs
  src/lnp/session/noise/hkdf.rs
  src/lnp/session/noise/mod.rs
  src/lnp/session/session.rs
  src/lnp/session/transcoders.rs
Labels: *privacy*, feature

#137 Some basic housekeeping in noise handshake
  src/lnp/session/noise/handshake.rs
Labels: documentation

#140 workflows/build: move matrix.os to new job "platforms"
  .github/workflows/build.yml
Labels: ci

#145 Expose rgb::stash::ExtensionData
  src/rgb/mod.rs
  src/rgb/stash/mod.rs
Labels: enhancement

#141 CI: add android + ios builds
  .github/workflows/build.yml
  Cargo.lock
  Cargo.toml
  README.md
Labels: ci

#147 add g++ and cmake to Debian requirements
  README.md
Labels: bug, ci

#150 Implement Autoconceal for other collection type
  src/rgb/contract/assignments.rs
  src/rgb/contract/conceal.rs
Labels: enhancement

#152 Autoconceal nits
  src/rgb/contract/conceal.rs
Labels: enhancement

#153 Add encoding to anchor id
  src/rgb/stash/anchor.rs
Labels: enhancement

#154 Moving onto master-branch dependency for all subcrates
  Cargo.lock
  Cargo.toml
  services/Cargo.toml
Labels: ci
